services:
# See https://docs.linuxserver.io/images/docker-sabnzbd/
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
#      - /mnt/share/data/usenet:/data/usenet:rw
      - /mnt/media/downloading/usenet:/data/usenet:rw
    ports:
      - 8080:8080
    restart: unless-stopped

# See https://docs.linuxserver.io/images/docker-bazarr/
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
#      - /mnt/share/data/media:/data/media
#      - /mnt/usb/data/media:/data/usb-media
      - /mnt/media:/data/media
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

#See https://docs.linuxserver.io/images/docker-lidarr/
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    ports:
      - "8686:8686"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/lidarr:/config
      - /mnt/share/data:/data
#      - /mnt/share/data/media:/data/media
#      - /mnt/usb/data/media:/data/usb-media
      - /mnt/media:/data/media
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

# See https://docs.linuxserver.io/images/docker-prowlarr/
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - "9696:9696"
    volumes:
      - /docker/appdata/prowlarr:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

# See https://docs.linuxserver.io/images/docker-radarr/
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /mnt/share/data:/data
#      - /mnt/share/data/media:/data/media
#      - /mnt/usb/data/media:/data/usb-media
      - /mnt/media:/data/media
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

# See https://docs.linuxserver.io/images/docker-sonarr/
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /mnt/share/data:/data
#      - /mnt/share/data/media:/data/media
#      - /mnt/usb/data/media:/data/usb-media
      - /mnt/media:/data/media
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

# See https://docs.linuxserver.io/images/jellyfin/
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - /docker/appdata/jellyfin/library:/config
#      - /mnt/share/data/media/tv:/data/tvshows
#      - /mnt/share/data/media/movies:/data/movies
#      - /mnt/usb/data/media/tv:/data/usb-tvshows
#      - /mnt/usb/data/media/movies:/data/usb-movies
      - /mnt/media/tv:/data/tvshows
      - /mnt/media/movies:/data/movies
      - /mnt/media/kids-movies:/data/kids-movies
      - /mnt/media/kids-tv:/data/kids-tv
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

# Jellyseerr
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/jellyseerr:/app/config
    restart: unless-stopped

networks:
  default:
    name: arrs
